version: '3.6'
services:
  web:
    build: .
    hostname: localhost
    image: iris-explorer:v1.1.0
    container_name: iris-explorer_web
    ports:
      - 80:80
  iris:
    hostname: localhost
    image: store/intersystems/iris-community:2019.4.0.383.0
    container_name: iris-explorer_iris
    volumes:
      - ${PWD}/shared/:/shared
    ports:
      - 55773:52773